version: 2
ethernets:
  default:
    match:
      driver: virtio*   # Match n'importe quelle interface virtio
    dhcp4: false
    dhcp6: false
    addresses:
      - ${ip}/24
    routes:
      - to: default
        via: ${gateway}/24
    nameservers:
      addresses:
        - 192.168.1.254
        - 8.8.8.8
