---
- name: Configure nodes
  hosts: control-plane, workers
  become: true

  pre_tasks:
    - name: Include common role
      ansible.builtin.include_role:
        name: ansible/k8s/roles/common
  tasks:

  roles:

  post_tasks: