version: 2
ethernets:
  default:
    match:
      driver: virtio*   # Match n'importe quelle interface virtio
    dhcp4: false   
    dhcp6: false
    addresses:
      - ${ip}
    routes:
      - to: default
        via: ${gateway}
    nameservers:
      addresses:
        - 192.168.1.254
