---
- name: Configure control-plane node
  hosts: control-plane
  become: true

  pre_tasks:
  
    - name: Ensure br_netfilter kernel module is loaded
      community.general.modprobe:
        name: br_netfilter
        state: present

    - name: sysctl persistent configuration
      ansible.builtin.copy:  
        src: k8s.conf
        dest: /etc/sysctl.d/k8s.conf

    - name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop: 
        - {'key': 'net.bridge.bridge-nf-call-ip6tables', 'value': 1}
        - {'key': 'net.bridge.bridge-nf-call-iptables', 'value': 1}

    - name: Add CRI-O and Kubernetes GPG keys
      ansible.builtin.deb822_repository:
        name: k8s
        types: deb
        uris: "https://pkgs.k8s.io/"
        suites: stable
        components: 
          - core
        architectures: amd64
        signed_by: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key"
     
  tasks:
  
  post_tasks:
  