---
- name: Configure control-plane node
  hosts: control-plane
  become: true

  vars:
    kubernetes_version: "v1.36"
    cri_o_version: "v1.36"

  pre_tasks:
  
    - name: Ensure br_netfilter kernel module is loaded
      community.general.modprobe:
        name: br_netfilter
        state: present

    - name: sysctl persistent configuration
      ansible.builtin.copy:  
        src: k8s.conf
        dest: /etc/sysctl.d/k8s.conf

    - name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop: 
        - { key: 'net.bridge.bridge-nf-call-ip6tables', value: 1 }
        - { key: 'net.bridge.bridge-nf-call-iptables', value: 1 }

    - name: Get Kubernetes and CRI-O GPG keys
      ansible.builtin.get_url:
        url: "{{ item.url }}Release.key"
        dest: "{{ item.dest }}"
        mode: '0644'
      register: keyrings
      loop:
        - { url: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/" , dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc } 
        - { url: "https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ cri_o_version }}/deb/", dest: /etc/apt/keyrings/cri-o-apt-keyring.asc }

    - name: Add deb repository CRI-O and Kubernetes with their GPG keys
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ item.item.dest }}] {{ item.item.url }} /"
        state: present
      loop: "{{ keyrings.results }}"

  tasks:
  
  post_tasks:
  